/* ================= Zarvan Gold — Database Schema Data (MySQL 8 / InnoDB / utf8mb4) ================= */

export type ColKey = "PK" | "FK" | "UQ" | "IX" | "";
export interface Col { n: string; t: string; k?: ColKey; ref?: string; d?: string }
export interface Table {
  name: string;
  desc: string;
  cols: Col[];
  idx?: string[];
  soft?: boolean;
  enums?: { col: string; values: string }[];
  group: string;
}
export interface Relation { from: string; to: string; type: "1-1" | "1-N" | "N-M"; via?: string; desc: string }

const C = (n: string, t: string, k: ColKey = "", ref?: string, d?: string): Col => ({ n, t, k, ref, d });

export const TABLES: Table[] = [
  /* ---------- Auth & Users ---------- */
  {
    name: "users", desc: "کاربران همه نقش‌ها (مشتری، نماینده، کارمند، مدیر)", group: "کاربران",
    soft: true,
    cols: [
      C("id", "BIGINT UNSIGNED", "PK"),
      C("name", "VARCHAR(60)", "", undefined, "nullable تا تکمیل پروفایل"),
      C("mobile", "VARCHAR(11)", "UQ", undefined, "09xxxxxxxxx"),
      C("email", "VARCHAR(120)", "UQ"),
      C("password_hash", "VARCHAR(255)", "", undefined, "nullable برای کاربران OTP-only"),
      C("role", "ENUM", "IX"),
      C("kyc_status", "ENUM", "IX"),
      C("referral_code", "VARCHAR(12)", "UQ"),
      C("referred_by", "BIGINT UNSIGNED", "FK", "users"),
      C("is_active", "TINYINT(1)", "", undefined, "default 1"),
      C("created_at", "TIMESTAMP"),
      C("updated_at", "TIMESTAMP"),
      C("deleted_at", "TIMESTAMP", "IX"),
    ],
    enums: [
      { col: "role", values: "customer, dealer, staff, admin" },
      { col: "kyc_status", values: "unverified, pending, approved, rejected" },
    ],
    idx: ["INDEX (kyc_status, created_at)"],
  },
  {
    name: "sessions", desc: "توکن‌های رفرش و نشست‌های دستگاه‌ها", group: "کاربران",
    cols: [
      C("id", "BIGINT UNSIGNED", "PK"),
      C("user_id", "BIGINT UNSIGNED", "FK", "users"),
      C("refresh_token_hash", "VARCHAR(64)", "UQ"),
      C("device", "VARCHAR(120)"),
      C("ip", "VARCHAR(45)"),
      C("last_active_at", "TIMESTAMP"),
      C("expires_at", "TIMESTAMP", "IX"),
      C("revoked_at", "TIMESTAMP", "", undefined, "nullable — ابطال"),
    ],
    idx: ["INDEX (user_id, revoked_at)"],
  },
  {
    name: "otp_codes", desc: "کدهای یکبارمصرف ورود، step-up و بازیابی رمز", group: "کاربران",
    cols: [
      C("id", "BIGINT UNSIGNED", "PK"),
      C("mobile", "VARCHAR(11)", "IX"),
      C("code_hash", "VARCHAR(64)"),
      C("purpose", "ENUM"),
      C("attempts", "TINYINT UNSIGNED", "", undefined, "default 0"),
      C("consumed_at", "TIMESTAMP"),
      C("expires_at", "TIMESTAMP", "IX"),
    ],
    enums: [{ col: "purpose", values: "login, withdraw, trade" }],
  },
  {
    name: "addresses", desc: "نشانی‌های تحویل کاربر", group: "کاربران",
    soft: true,
    cols: [
      C("id", "BIGINT UNSIGNED", "PK"),
      C("user_id", "BIGINT UNSIGNED", "FK", "users"),
      C("title", "VARCHAR(40)"),
      C("province", "VARCHAR(40)"),
      C("city", "VARCHAR(40)"),
      C("line1", "VARCHAR(255)"),
      C("postal_code", "VARCHAR(10)"),
      C("is_default", "TINYINT(1)", "", undefined, "default 0"),
      C("created_at", "TIMESTAMP"),
    ],
    idx: ["INDEX (user_id)"],
  },
  {
    name: "notification_preferences", desc: "ترجیحات کانال اعلان — یک ردیف per user", group: "کاربران",
    cols: [
      C("user_id", "BIGINT UNSIGNED", "PK", "users"),
      C("sms", "TINYINT(1)", "", undefined, "default 1"),
      C("email", "TINYINT(1)", "", undefined, "default 1"),
      C("in_app", "TINYINT(1)", "", undefined, "default 1"),
      C("price_alerts", "TINYINT(1)", "", undefined, "default 1"),
    ],
  },
  {
    name: "user_sizes", desc: "سایز ذخیره‌شده انگشتر/دستبند از راهنمای سایز", group: "کاربران",
    cols: [
      C("id", "BIGINT UNSIGNED", "PK"),
      C("user_id", "BIGINT UNSIGNED", "FK", "users"),
      C("kind", "ENUM"),
      C("value_mm", "SMALLINT UNSIGNED"),
      C("saved_at", "TIMESTAMP"),
    ],
    enums: [{ col: "kind", values: "ring, bracelet" }],
    idx: ["UNIQUE (user_id, kind)"],
  },
  {
    name: "kyc_submissions", desc: "آخرین وضعیت احراز هویت هر کاربر", group: "کاربران",
    cols: [
      C("id", "BIGINT UNSIGNED", "PK"),
      C("user_id", "BIGINT UNSIGNED", "UQ", "users"),
      C("status", "ENUM", "IX"),
      C("submitted_at", "TIMESTAMP"),
      C("reviewed_at", "TIMESTAMP"),
      C("reviewed_by", "BIGINT UNSIGNED", "FK", "users"),
      C("reject_reason", "VARCHAR(255)"),
    ],
    enums: [{ col: "status", values: "unverified, pending, approved, rejected" }],
  },
  {
    name: "kyc_documents", desc: "فایل‌های مدارک (کارت ملی، سلفی، عکس بازخرید)", group: "کاربران",
    soft: true,
    cols: [
      C("id", "BIGINT UNSIGNED", "PK"),
      C("user_id", "BIGINT UNSIGNED", "FK", "users"),
      C("kind", "ENUM"),
      C("file_path", "VARCHAR(255)"),
      C("mime", "VARCHAR(40)"),
      C("size_kb", "INT UNSIGNED"),
      C("status", "ENUM", "", undefined, "pending/accepted/rejected"),
      C("created_at", "TIMESTAMP"),
    ],
    enums: [{ col: "kind", values: "national_id_front, national_id_back, selfie, buyback_photo" }],
    idx: ["INDEX (user_id, kind)"],
  },
  {
    name: "referrals", desc: "رابطه معرف ← معرف‌شده + پاداش‌ها", group: "کاربران",
    cols: [
      C("id", "BIGINT UNSIGNED", "PK"),
      C("referrer_id", "BIGINT UNSIGNED", "FK", "users"),
      C("referee_id", "BIGINT UNSIGNED", "UQ", "users"),
      C("code", "VARCHAR(12)", "IX"),
      C("joined_at", "TIMESTAMP"),
      C("reward_status", "ENUM"),
      C("reward_gold_mg", "INT UNSIGNED", "", undefined, "default 1200"),
      C("paid_at", "TIMESTAMP"),
    ],
    enums: [{ col: "reward_status", values: "pending, paid" }],
  },

  /* ---------- Catalog ---------- */
  {
    name: "categories", desc: "دسته‌بندی درختی محصولات (حداکثر ۲ سطح)", group: "کاتالوگ",
    soft: true,
    cols: [
      C("id", "BIGINT UNSIGNED", "PK"),
      C("parent_id", "BIGINT UNSIGNED", "FK", "categories"),
      C("name", "VARCHAR(60)"),
      C("slug", "VARCHAR(60)", "UQ"),
      C("type", "ENUM", "IX"),
      C("sort_order", "SMALLINT UNSIGNED", "", undefined, "default 0"),
      C("is_active", "TINYINT(1)", "", undefined, "default 1"),
    ],
    enums: [{ col: "type", values: "jewelry, bullion, melted" }],
  },
  {
    name: "products", desc: "محصولات: جواهرات، شمش، سکه و طلای آب‌شده", group: "کاتالوگ",
    soft: true,
    cols: [
      C("id", "BIGINT UNSIGNED", "PK"),
      C("sku", "VARCHAR(32)", "UQ", undefined, "مثل BR-18-221"),
      C("slug", "VARCHAR(120)", "UQ"),
      C("name", "VARCHAR(120)"),
      C("type", "ENUM", "IX"),
      C("category_id", "BIGINT UNSIGNED", "FK", "categories"),
      C("karat", "ENUM", "IX", undefined, "18 | 24"),
      C("weight_mg", "INT UNSIGNED"),
      C("making_charge_type", "ENUM", "", undefined, "flat | per_gram"),
      C("making_charge_irr", "BIGINT UNSIGNED", "", undefined, "ریال — 0 برای سکه"),
      C("occasion", "VARCHAR(30)", "IX", undefined, "هدیه/نامزدی/ازدواج/جهیزیه"),
      C("status", "ENUM", "IX"),
      C("description", "TEXT"),
      C("attributes", "JSON", "", undefined, "مشخصات آزاد"),
      C("has_360", "TINYINT(1)", "", undefined, "default 0"),
      C("published_at", "TIMESTAMP"),
      C("created_at", "TIMESTAMP"),
    ],
    enums: [
      { col: "type", values: "jewelry, bar, coin, melted" },
      { col: "status", values: "draft, active, inactive, out_of_stock" },
    ],
    idx: ["FULLTEXT (name)", "INDEX (status, type, karat)"],
  },
  {
    name: "product_images", desc: "گالری تصاویر محصول", group: "کاتالوگ",
    cols: [
      C("id", "BIGINT UNSIGNED", "PK"),
      C("product_id", "BIGINT UNSIGNED", "FK", "products"),
      C("url", "VARCHAR(255)"),
      C("alt", "VARCHAR(120)"),
      C("sort_order", "TINYINT UNSIGNED"),
    ],
    idx: ["INDEX (product_id, sort_order)"],
  },
  {
    name: "product_360_frames", desc: "فریم‌های نمای ۳۶۰ (۲۴ فریم per محصول)", group: "کاتالوگ",
    cols: [
      C("id", "BIGINT UNSIGNED", "PK"),
      C("product_id", "BIGINT UNSIGNED", "FK", "products"),
      C("frame_no", "TINYINT UNSIGNED"),
      C("url", "VARCHAR(255)"),
    ],
    idx: ["UNIQUE (product_id, frame_no)"],
  },
  {
    name: "wishlists", desc: "علاقه‌مندی‌های کاربر — pivot محصول", group: "کاتالوگ",
    cols: [
      C("user_id", "BIGINT UNSIGNED", "PK", "users"),
      C("product_id", "BIGINT UNSIGNED", "PK", "products"),
      C("created_at", "TIMESTAMP"),
    ],
  },
  {
    name: "restock_notifies", desc: "اشتراک «به من خبر بده» برای کالای ناموجود", group: "کاتالوگ",
    cols: [
      C("user_id", "BIGINT UNSIGNED", "PK", "users"),
      C("product_id", "BIGINT UNSIGNED", "PK", "products"),
      C("notified_at", "TIMESTAMP", "", undefined, "null تا ارسال اطلاعیه"),
    ],
  },

  /* ---------- Inventory & Vault ---------- */
  {
    name: "inventories", desc: "موجودی فیزیکی هر SKU + نقطه سفارش", group: "انبار و خزانه",
    cols: [
      C("product_id", "BIGINT UNSIGNED", "PK", "products"),
      C("on_hand", "INT UNSIGNED", "", undefined, "default 0"),
      C("reserved", "INT UNSIGNED", "", undefined, "default 0 — رزرو سبد/سفارش"),
      C("reorder_point", "INT UNSIGNED", "", undefined, "default 0"),
      C("updated_at", "TIMESTAMP"),
    ],
  },
  {
    name: "stock_movements", desc: "گردش موجودی با دلیل (فروش، تصحیح، ورود لات)", group: "انبار و خزانه",
    cols: [
      C("id", "BIGINT UNSIGNED", "PK"),
      C("product_id", "BIGINT UNSIGNED", "FK", "products"),
      C("delta", "INT", "", undefined, "مثبت/منفی"),
      C("reason", "ENUM", "IX"),
      C("actor_id", "BIGINT UNSIGNED", "FK", "users"),
      C("note", "VARCHAR(255)"),
      C("created_at", "TIMESTAMP", "IX"),
    ],
    enums: [{ col: "reason", values: "sale, reserve, release, correction, inbound" }],
  },
  {
    name: "vault_lots", desc: "لات‌های طلای فیزیکی خزانه برای سنجش کفایت", group: "انبار و خزانه",
    cols: [
      C("id", "BIGINT UNSIGNED", "PK"),
      C("karat", "ENUM"),
      C("weight_mg", "BIGINT UNSIGNED"),
      C("serial", "VARCHAR(30)", "UQ"),
      C("cost_irr", "BIGINT UNSIGNED"),
      C("stored_at", "TIMESTAMP"),
    ],
    enums: [{ col: "karat", values: "18, 24" }],
  },

  /* ---------- Pricing ---------- */
  {
    name: "price_settings", desc: "تنظیمات قیمت‌گذاری — تک‌ردیفی", group: "قیمت",
    cols: [
      C("id", "TINYINT UNSIGNED", "PK", undefined, "همیشه 1"),
      C("bid_bps", "SMALLINT UNSIGNED", "", undefined, "default 60"),
      C("ask_bps", "SMALLINT UNSIGNED", "", undefined, "default 45"),
      C("quote_ttl_sec", "TINYINT UNSIGNED", "", undefined, "default 18"),
      C("slippage_bps", "TINYINT UNSIGNED", "", undefined, "default 10"),
      C("trading_halt", "TINYINT(1)", "", undefined, "default 0"),
      C("updated_at", "TIMESTAMP"),
    ],
  },
  {
    name: "spot_prices", desc: "آخرین نرخ هر عیار (فید بازار یا دستی)", group: "قیمت",
    cols: [
      C("karat", "ENUM", "PK", undefined, "18 | 24"),
      C("price_irr_per_gram", "BIGINT UNSIGNED"),
      C("source", "ENUM", "", undefined, "feed | manual"),
      C("observed_at", "TIMESTAMP"),
    ],
    enums: [{ col: "source", values: "feed, manual" }],
  },
  {
    name: "price_snapshots", desc: "تاریخچه نرخ‌ها — partition ماهانه برای نمودارها", group: "قیمت",
    cols: [
      C("id", "BIGINT UNSIGNED", "PK"),
      C("karat", "ENUM", "IX"),
      C("price_irr", "BIGINT UNSIGNED"),
      C("t", "TIMESTAMP(3)", "IX", undefined, "زمان ثبت"),
    ],
    idx: ["INDEX (karat, t)", "PARTITION BY RANGE (TO_DAYS(t)) — ماهانه"],
  },
  {
    name: "price_alerts", desc: "هشدار عبور قیمت از آستانه", group: "قیمت",
    cols: [
      C("id", "BIGINT UNSIGNED", "PK"),
      C("user_id", "BIGINT UNSIGNED", "FK", "users"),
      C("karat", "ENUM"),
      C("direction", "ENUM"),
      C("threshold_irr", "BIGINT UNSIGNED"),
      C("is_active", "TINYINT(1)", "", undefined, "default 1"),
      C("triggered_at", "TIMESTAMP", "", undefined, "آخرین تحریک"),
    ],
    enums: [{ col: "direction", values: "above, below" }],
    idx: ["INDEX (is_active, karat, direction, threshold_irr)"],
  },

  /* ---------- Wallets ---------- */
  {
    name: "wallets", desc: "دو کیف پول per کاربر: ریال و طلای میلی‌گرمی", group: "کیف پول",
    cols: [
      C("id", "BIGINT UNSIGNED", "PK"),
      C("user_id", "BIGINT UNSIGNED", "FK", "users"),
      C("currency", "ENUM"),
      C("balance", "BIGINT UNSIGNED", "", undefined, "ریال یا mg — CHECK ≥ 0"),
      C("updated_at", "TIMESTAMP"),
    ],
    enums: [{ col: "currency", values: "irr, gold_mg" }],
    idx: ["UNIQUE (user_id, currency)"],
  },
  {
    name: "wallet_ledgers", desc: "گردش تغییرناپذیر (append-only) کیف پول", group: "کیف پول",
    cols: [
      C("id", "BIGINT UNSIGNED", "PK"),
      C("wallet_id", "BIGINT UNSIGNED", "FK", "wallets"),
      C("direction", "ENUM", "IX"),
      C("amount", "BIGINT UNSIGNED"),
      C("reason", "VARCHAR(120)"),
      C("balance_after", "BIGINT UNSIGNED"),
      C("reference_type", "VARCHAR(30)", "IX", undefined, "trade | deposit | order | gift | …"),
      C("reference_id", "BIGINT UNSIGNED"),
      C("actor_id", "BIGINT UNSIGNED", "FK", "users", "کارمند در اصلاح دستی"),
      C("created_at", "TIMESTAMP(3)", "IX"),
    ],
    enums: [{ col: "direction", values: "credit, debit" }],
    idx: ["INDEX (wallet_id, created_at)"],
  },
  {
    name: "deposits", desc: "واریزها از درگاه PSP", group: "کیف پول",
    cols: [
      C("id", "BIGINT UNSIGNED", "PK"),
      C("user_id", "BIGINT UNSIGNED", "FK", "users"),
      C("amount_irr", "BIGINT UNSIGNED"),
      C("status", "ENUM", "IX"),
      C("driver", "VARCHAR(30)"),
      C("authority", "VARCHAR(64)"),
      C("ref_id", "VARCHAR(64)"),
      C("paid_at", "TIMESTAMP"),
      C("created_at", "TIMESTAMP"),
    ],
    enums: [{ col: "status", values: "pending, paid, failed, cancelled" }],
  },
  {
    name: "withdrawals", desc: "برداشت‌ها به شبا با تأیید OTP", group: "کیف پول",
    cols: [
      C("id", "BIGINT UNSIGNED", "PK"),
      C("user_id", "BIGINT UNSIGNED", "FK", "users"),
      C("amount_irr", "BIGINT UNSIGNED"),
      C("iban", "VARCHAR(26)"),
      C("status", "ENUM", "IX"),
      C("settled_at", "TIMESTAMP"),
      C("created_at", "TIMESTAMP"),
    ],
    enums: [{ col: "status", values: "pending, settled, rejected" }],
  },

  /* ---------- Trading ---------- */
  {
    name: "trade_quotes", desc: "نقل‌قول‌های محدود به TTL", group: "معامله",
    cols: [
      C("id", "BIGINT UNSIGNED", "PK"),
      C("user_id", "BIGINT UNSIGNED", "FK", "users"),
      C("side", "ENUM"),
      C("weight_mg", "INT UNSIGNED"),
      C("spot_irr", "BIGINT UNSIGNED"),
      C("spread_bps", "SMALLINT UNSIGNED"),
      C("irr_amount", "BIGINT UNSIGNED"),
      C("status", "ENUM", "IX", undefined, "active | used | expired"),
      C("expires_at", "TIMESTAMP", "IX"),
      C("created_at", "TIMESTAMP"),
    ],
    enums: [{ col: "side", values: "buy, sell" }],
  },
  {
    name: "trades", desc: "معامله‌های انجام‌شده طلای آب‌شده", group: "معامله",
    cols: [
      C("id", "BIGINT UNSIGNED", "PK"),
      C("user_id", "BIGINT UNSIGNED", "FK", "users"),
      C("quote_id", "BIGINT UNSIGNED", "FK", "trade_quotes"),
      C("side", "ENUM", "IX"),
      C("status", "ENUM", "", undefined, "filled | rejected"),
      C("weight_mg", "INT UNSIGNED"),
      C("irr_amount", "BIGINT UNSIGNED"),
      C("spot_irr", "BIGINT UNSIGNED"),
      C("slippage_bps", "SMALLINT UNSIGNED"),
      C("filled_at", "TIMESTAMP", "IX"),
    ],
    enums: [{ col: "side", values: "buy, sell" }, { col: "status", values: "filled, rejected" }],
  },
  {
    name: "buyback_requests", desc: "بازخرید از کیف پول یا طلای فیزیکی", group: "معامله",
    cols: [
      C("id", "BIGINT UNSIGNED", "PK"),
      C("user_id", "BIGINT UNSIGNED", "FK", "users"),
      C("source", "ENUM", "IX"),
      C("weight_mg", "INT UNSIGNED"),
      C("estimated_irr", "BIGINT UNSIGNED"),
      C("final_irr", "BIGINT UNSIGNED"),
      C("status", "ENUM", "IX", undefined, "pending | settled | rejected"),
      C("photo_id", "BIGINT UNSIGNED", "FK", "kyc_documents"),
      C("notes", "VARCHAR(255)"),
      C("created_at", "TIMESTAMP"),
    ],
    enums: [{ col: "source", values: "wallet, physical" }],
  },
  {
    name: "portfolio_lots", desc: "لات‌های خرید برای محاسبه بهای تمام‌شده (FIFO)", group: "معامله",
    cols: [
      C("id", "BIGINT UNSIGNED", "PK"),
      C("user_id", "BIGINT UNSIGNED", "FK", "users"),
      C("trade_id", "BIGINT UNSIGNED", "FK", "trades"),
      C("acquired_at", "TIMESTAMP", "IX"),
      C("weight_mg", "INT UNSIGNED"),
      C("cost_irr", "BIGINT UNSIGNED"),
    ],
  },
  {
    name: "auto_invest_plans", desc: "برنامه‌های خرید پله‌ای ماهانه", group: "معامله",
    cols: [
      C("id", "BIGINT UNSIGNED", "PK"),
      C("user_id", "BIGINT UNSIGNED", "FK", "users"),
      C("amount_irr", "BIGINT UNSIGNED"),
      C("day_of_month", "TINYINT UNSIGNED", "", undefined, "1..28"),
      C("is_active", "TINYINT(1)", "", undefined, "default 1"),
      C("last_run_at", "TIMESTAMP"),
      C("created_at", "TIMESTAMP"),
    ],
  },
  {
    name: "installment_contracts", desc: "قراردادهای اقساطی خرید", group: "معامله",
    cols: [
      C("id", "BIGINT UNSIGNED", "PK"),
      C("user_id", "BIGINT UNSIGNED", "FK", "users"),
      C("order_id", "BIGINT UNSIGNED", "FK", "orders"),
      C("months", "TINYINT UNSIGNED"),
      C("down_irr", "BIGINT UNSIGNED"),
      C("principal_irr", "BIGINT UNSIGNED"),
      C("paid_irr", "BIGINT UNSIGNED", "", undefined, "default 0"),
      C("status", "ENUM", "IX", undefined, "active | completed | defaulted"),
      C("created_at", "TIMESTAMP"),
    ],
  },
  {
    name: "installment_payments", desc: "اقساط پرداخت‌شده", group: "معامله",
    cols: [
      C("id", "BIGINT UNSIGNED", "PK"),
      C("contract_id", "BIGINT UNSIGNED", "FK", "installment_contracts"),
      C("amount_irr", "BIGINT UNSIGNED"),
      C("method", "ENUM", "", undefined, "wallet | gateway"),
      C("paid_at", "TIMESTAMP"),
    ],
  },

  /* ---------- Commerce ---------- */
  {
    name: "carts", desc: "سبد خرید فعال هر کاربر", group: "فروش",
    cols: [
      C("id", "BIGINT UNSIGNED", "PK"),
      C("user_id", "BIGINT UNSIGNED", "UQ", "users", "یک سبد فعال per user"),
      C("status", "ENUM", "IX", undefined, "active | converted | abandoned"),
      C("coupon_id", "BIGINT UNSIGNED", "FK", "coupons"),
      C("quote_expires_at", "TIMESTAMP", "", undefined, "قفل قیمت Checkout"),
      C("updated_at", "TIMESTAMP"),
    ],
  },
  {
    name: "cart_lines", desc: "اقلام سبد با قیمت قفل‌شده لحظه‌ی افزودن", group: "فروش",
    cols: [
      C("id", "BIGINT UNSIGNED", "PK"),
      C("cart_id", "BIGINT UNSIGNED", "FK", "carts"),
      C("product_id", "BIGINT UNSIGNED", "FK", "products"),
      C("qty", "TINYINT UNSIGNED"),
      C("packaging", "ENUM", "", undefined, "standard | luxury"),
      C("unit_quote_irr", "BIGINT UNSIGNED"),
    ],
    idx: ["UNIQUE (cart_id, product_id)"],
  },
  {
    name: "coupons", desc: "کدهای تخفیف درصدی یا ثابت", group: "فروش",
    cols: [
      C("id", "BIGINT UNSIGNED", "PK"),
      C("code", "VARCHAR(24)", "UQ"),
      C("type", "ENUM"),
      C("value", "INT UNSIGNED", "", undefined, "درصد یا ریال"),
      C("max_uses", "INT UNSIGNED"),
      C("uses_count", "INT UNSIGNED", "", undefined, "default 0"),
      C("min_order_irr", "BIGINT UNSIGNED"),
      C("expires_at", "TIMESTAMP"),
      C("is_active", "TINYINT(1)", "", undefined, "default 1"),
    ],
    enums: [{ col: "type", values: "percent, fixed_irr" }],
  },
  {
    name: "coupon_redemptions", desc: "pivot مصرف کوپن per کاربر/سفارش", group: "فروش",
    cols: [
      C("coupon_id", "BIGINT UNSIGNED", "PK", "coupons"),
      C("user_id", "BIGINT UNSIGNED", "PK", "users"),
      C("order_id", "BIGINT UNSIGNED", "FK", "orders"),
      C("discount_irr", "BIGINT UNSIGNED"),
      C("redeemed_at", "TIMESTAMP"),
    ],
  },
  {
    name: "orders", desc: "سفارش‌ها با وضعیت و نوع تحقق (خزانه/تحویل)", group: "فروش",
    soft: true,
    cols: [
      C("id", "BIGINT UNSIGNED", "PK"),
      C("user_id", "BIGINT UNSIGNED", "FK", "users"),
      C("number", "VARCHAR(20)", "UQ", undefined, "ZRVORD-YYYY-####"),
      C("status", "ENUM", "IX"),
      C("fulfillment", "ENUM", "IX"),
      C("address_id", "BIGINT UNSIGNED", "FK", "addresses"),
      C("coupon_id", "BIGINT UNSIGNED", "FK", "coupons"),
      C("subtotal_irr", "BIGINT UNSIGNED"),
      C("making_irr", "BIGINT UNSIGNED", "", undefined, "default 0"),
      C("discount_irr", "BIGINT UNSIGNED", "", undefined, "default 0"),
      C("tax_irr", "BIGINT UNSIGNED", "", undefined, "default 0"),
      C("total_irr", "BIGINT UNSIGNED"),
      C("gold_mg", "INT UNSIGNED"),
      C("reserve_expires_at", "TIMESTAMP", "", undefined, "برای سفارش بیعانه‌ای"),
      C("paid_at", "TIMESTAMP"),
      C("created_at", "TIMESTAMP", "IX"),
    ],
    enums: [
      { col: "status", values: "draft, awaiting_payment, paid, reserved, processing, vaulted, shipped, delivered, cancelled, refunded" },
      { col: "fulfillment", values: "vault, delivery" },
    ],
    idx: ["INDEX (user_id, status)", "INDEX (created_at)"],
  },
  {
    name: "order_items", desc: "اقلام سفارش — snapshot محصول و قیمت", group: "فروش",
    cols: [
      C("id", "BIGINT UNSIGNED", "PK"),
      C("order_id", "BIGINT UNSIGNED", "FK", "orders"),
      C("product_id", "BIGINT UNSIGNED", "FK", "products"),
      C("qty", "TINYINT UNSIGNED"),
      C("packaging", "ENUM"),
      C("unit_price_irr", "BIGINT UNSIGNED"),
      C("weight_mg", "INT UNSIGNED", "", undefined, "snapshot وزن"),
    ],
    enums: [{ col: "packaging", values: "standard, luxury" }],
  },
  {
    name: "shipments", desc: "مرسوله‌های تحویل فیزیکی", group: "فروش",
    cols: [
      C("id", "BIGINT UNSIGNED", "PK"),
      C("order_id", "BIGINT UNSIGNED", "UQ", "orders"),
      C("carrier", "VARCHAR(40)"),
      C("tracking_code", "VARCHAR(40)", "IX"),
      C("status", "ENUM", "IX", undefined, "preparing | shipped | delivered"),
      C("shipped_at", "TIMESTAMP"),
      C("delivered_at", "TIMESTAMP"),
    ],
  },
  {
    name: "shipment_events", desc: "رویدادهای timeline مرسوله", group: "فروش",
    cols: [
      C("id", "BIGINT UNSIGNED", "PK"),
      C("shipment_id", "BIGINT UNSIGNED", "FK", "shipments"),
      C("label", "VARCHAR(120)"),
      C("at", "TIMESTAMP"),
    ],
  },
  {
    name: "payments", desc: "تراکنش‌های درگاه و کیف پول", group: "فروش",
    cols: [
      C("id", "BIGINT UNSIGNED", "PK"),
      C("user_id", "BIGINT UNSIGNED", "FK", "users"),
      C("order_id", "BIGINT UNSIGNED", "FK", "orders"),
      C("amount_irr", "BIGINT UNSIGNED"),
      C("driver", "VARCHAR(30)", "IX", undefined, "wallet | behpardakht | zarinpal"),
      C("status", "ENUM", "IX"),
      C("authority", "VARCHAR(64)"),
      C("ref_id", "VARCHAR(64)", "IX"),
      C("paid_at", "TIMESTAMP"),
      C("created_at", "TIMESTAMP"),
    ],
    enums: [{ col: "status", values: "pending, paid, failed, cancelled" }],
  },
  {
    name: "payment_refunds", desc: "بازپرداخت‌های ثبت‌شده توسط ادمین", group: "فروش",
    cols: [
      C("id", "BIGINT UNSIGNED", "PK"),
      C("payment_id", "BIGINT UNSIGNED", "FK", "payments"),
      C("amount_irr", "BIGINT UNSIGNED"),
      C("reason", "VARCHAR(255)"),
      C("actor_id", "BIGINT UNSIGNED", "FK", "users"),
      C("refunded_at", "TIMESTAMP"),
    ],
  },
  {
    name: "invoices", desc: "فاکتورهای رسمی خرید و معامله", group: "فروش",
    cols: [
      C("id", "BIGINT UNSIGNED", "PK"),
      C("user_id", "BIGINT UNSIGNED", "FK", "users"),
      C("order_id", "BIGINT UNSIGNED", "FK", "orders"),
      C("number", "VARCHAR(20)", "UQ", undefined, "ZRV-YYYY-#####"),
      C("issued_at", "TIMESTAMP", "IX"),
      C("total_irr", "BIGINT UNSIGNED"),
      C("gold_mg", "INT UNSIGNED"),
      C("pdf_path", "VARCHAR(255)"),
    ],
  },
  {
    name: "delivery_requests", desc: "تبدیل طلای خزانه به شمش فیزیکی", group: "فروش",
    cols: [
      C("id", "BIGINT UNSIGNED", "PK"),
      C("user_id", "BIGINT UNSIGNED", "FK", "users"),
      C("weight_mg", "INT UNSIGNED"),
      C("bar_size", "ENUM", "", undefined, "5g | 10g | 50g"),
      C("address_id", "BIGINT UNSIGNED", "FK", "addresses"),
      C("fee_irr", "BIGINT UNSIGNED"),
      C("status", "ENUM", "IX", undefined, "pending | minting | shipped | delivered"),
      C("tracking_code", "VARCHAR(40)"),
      C("created_at", "TIMESTAMP"),
    ],
  },
  {
    name: "gift_cards", desc: "کارت هدیه طلا با کد یکتا", group: "فروش",
    cols: [
      C("id", "BIGINT UNSIGNED", "PK"),
      C("sender_id", "BIGINT UNSIGNED", "FK", "users"),
      C("code", "VARCHAR(16)", "UQ", undefined, "ZGIFT-XXXXX"),
      C("recipient_mobile", "VARCHAR(11)", "IX"),
      C("recipient_id", "BIGINT UNSIGNED", "FK", "users", "پس از claim"),
      C("gold_mg", "INT UNSIGNED"),
      C("status", "ENUM", "IX"),
      C("packaging", "ENUM"),
      C("message", "VARCHAR(200)"),
      C("claimed_at", "TIMESTAMP"),
      C("created_at", "TIMESTAMP"),
    ],
    enums: [{ col: "status", values: "created, sent, redeemed" }],
  },
  {
    name: "wholesale_orders", desc: "سفارش‌های عمده نمایندگان", group: "فروش",
    cols: [
      C("id", "BIGINT UNSIGNED", "PK"),
      C("user_id", "BIGINT UNSIGNED", "FK", "users", "نماینده"),
      C("number", "VARCHAR(20)", "UQ", undefined, "ZRVWHL-YYYY-###"),
      C("qty_mg", "INT UNSIGNED"),
      C("total_irr", "BIGINT UNSIGNED"),
      C("delivery_schedule", "JSON", "", undefined, "تاریخ‌های تحویل پلکانی"),
      C("status", "ENUM", "IX", undefined, "pending | processing | delivered"),
      C("created_at", "TIMESTAMP"),
    ],
  },

  /* ---------- Support & Comms ---------- */
  {
    name: "tickets", desc: "تیکت‌های پشتیبانی", group: "پشتیبانی",
    cols: [
      C("id", "BIGINT UNSIGNED", "PK"),
      C("user_id", "BIGINT UNSIGNED", "FK", "users"),
      C("assignee_id", "BIGINT UNSIGNED", "FK", "users", "کارمند پاسخگو"),
      C("subject", "VARCHAR(120)"),
      C("type", "ENUM", "IX"),
      C("status", "ENUM", "IX"),
      C("priority", "ENUM", "IX"),
      C("updated_at", "TIMESTAMP", "IX"),
      C("created_at", "TIMESTAMP"),
    ],
    enums: [
      { col: "type", values: "general, price_match, delivery, kyc" },
      { col: "status", values: "open, pending, closed" },
      { col: "priority", values: "low, normal, high" },
    ],
  },
  {
    name: "ticket_messages", desc: "گفتگوی تیکت — is_staff متمایزکننده طرف", group: "پشتیبانی",
    cols: [
      C("id", "BIGINT UNSIGNED", "PK"),
      C("ticket_id", "BIGINT UNSIGNED", "FK", "tickets"),
      C("author_id", "BIGINT UNSIGNED", "FK", "users"),
      C("body", "TEXT"),
      C("is_staff", "TINYINT(1)"),
      C("created_at", "TIMESTAMP", "IX"),
    ],
  },
  {
    name: "notifications", desc: "اعلان‌های درون‌برنامه", group: "پشتیبانی",
    cols: [
      C("id", "BIGINT UNSIGNED", "PK"),
      C("user_id", "BIGINT UNSIGNED", "FK", "users"),
      C("type", "VARCHAR(20)", "IX", undefined, "trade | price | order | promo | system | kyc"),
      C("title", "VARCHAR(120)"),
      C("body", "VARCHAR(500)"),
      C("data", "JSON", "", undefined, "لینک عمیق — trade_id و…"),
      C("read_at", "TIMESTAMP"),
      C("created_at", "TIMESTAMP", "IX"),
    ],
    idx: ["INDEX (user_id, read_at)"],
  },
  {
    name: "broadcast_messages", desc: "اعلان‌های همگانی ادمین", group: "پشتیبانی",
    cols: [
      C("id", "BIGINT UNSIGNED", "PK"),
      C("title", "VARCHAR(80)"),
      C("body", "VARCHAR(500)"),
      C("channels", "JSON", "", undefined, "in_app/sms/email"),
      C("audience", "VARCHAR(30)", "", undefined, "all | verified | dealers"),
      C("recipients", "INT UNSIGNED"),
      C("actor_id", "BIGINT UNSIGNED", "FK", "users"),
      C("sent_at", "TIMESTAMP"),
    ],
  },

  /* ---------- System ---------- */
  {
    name: "settings", desc: "تنظیمات سراسری سامانه — تک‌ردیفی", group: "سیستم",
    cols: [
      C("id", "TINYINT UNSIGNED", "PK", undefined, "همیشه 1"),
      C("min_trade_mg", "INT UNSIGNED", "", undefined, "default 100"),
      C("unverified_daily_cap_irr", "BIGINT UNSIGNED", "", undefined, "default 50,000,000"),
      C("otp_enabled", "TINYINT(1)", "", undefined, "default 1"),
      C("vat_pct", "DECIMAL(4,2)", "", undefined, "default 0"),
      C("invoice_legal_name", "VARCHAR(120)"),
      C("invoice_reg_no", "VARCHAR(30)"),
      C("psp", "VARCHAR(40)"),
      C("sms_provider", "VARCHAR(40)"),
      C("vault_address", "VARCHAR(255)"),
      C("maintenance", "TINYINT(1)", "", undefined, "default 0"),
      C("updated_at", "TIMESTAMP"),
    ],
  },
  {
    name: "audit_logs", desc: "ردپای عملیات حساس ادمین/کارمند", group: "سیستم",
    cols: [
      C("id", "BIGINT UNSIGNED", "PK"),
      C("actor_id", "BIGINT UNSIGNED", "FK", "users"),
      C("action", "VARCHAR(60)", "IX", undefined, "settings.update | wallet.adjust | …"),
      C("payload", "JSON"),
      C("ip", "VARCHAR(45)"),
      C("at", "TIMESTAMP(3)", "IX"),
    ],
  },
  {
    name: "staff_invites", desc: "دعوت‌نامه‌های کارکنان", group: "سیستم",
    cols: [
      C("id", "BIGINT UNSIGNED", "PK"),
      C("mobile", "VARCHAR(11)"),
      C("role", "ENUM", "", undefined, "staff | admin"),
      C("invited_by", "BIGINT UNSIGNED", "FK", "users"),
      C("accepted_at", "TIMESTAMP"),
      C("expires_at", "TIMESTAMP"),
    ],
  },
];

export const RELATIONS: Relation[] = [
  { from: "users", to: "wallets", type: "1-N", desc: "هر کاربر دقیقاً دو کیف پول (irr, gold_mg)" },
  { from: "wallets", to: "wallet_ledgers", type: "1-N", desc: "گردش append-only هر کیف پول" },
  { from: "users", to: "addresses", type: "1-N", desc: "نشانی‌های تحویل" },
  { from: "users", to: "kyc_submissions", type: "1-1", desc: "آخرین وضعیت احراز هویت" },
  { from: "kyc_submissions", to: "kyc_documents", type: "1-N", desc: "مدارک بارگذاری‌شده" },
  { from: "users", to: "referrals", type: "1-N", desc: "معرفی‌شده‌های هر کاربر (referrer)" },
  { from: "users", to: "users", type: "1-N", desc: "referred_by — خودارجاعی معرف" },
  { from: "categories", to: "categories", type: "1-N", desc: "parent_id — درخت دسته‌ها" },
  { from: "categories", to: "products", type: "1-N", desc: "محصولات هر دسته" },
  { from: "products", to: "product_images", type: "1-N", desc: "گالری" },
  { from: "products", to: "product_360_frames", type: "1-N", desc: "فریم‌های ۳۶۰" },
  { from: "products", to: "inventories", type: "1-1", desc: "موجودی و رزرو هر SKU" },
  { from: "users", to: "wishlists", type: "N-M", via: "wishlists", desc: "علاقه‌مندی‌ها" },
  { from: "products", to: "wishlists", type: "N-M", via: "wishlists", desc: "محصولات نشان‌شده" },
  { from: "users", to: "trade_quotes", type: "1-N", desc: "نقل‌قول‌های دریافتی" },
  { from: "trade_quotes", to: "trades", type: "1-1", desc: "اجرای Quote" },
  { from: "users", to: "trades", type: "1-N", desc: "معاملات کاربر" },
  { from: "trades", to: "portfolio_lots", type: "1-1", desc: "لات خرید به ازای معامله buy" },
  { from: "users", to: "carts", type: "1-1", desc: "سبد فعال" },
  { from: "carts", to: "cart_lines", type: "1-N", desc: "اقلام سبد" },
  { from: "products", to: "cart_lines", type: "1-N", desc: "محصول در سبدها" },
  { from: "coupons", to: "coupon_redemptions", type: "1-N", desc: "مصرف کوپن" },
  { from: "users", to: "orders", type: "1-N", desc: "سفارش‌های مشتری" },
  { from: "orders", to: "order_items", type: "1-N", desc: "اقلام سفارش" },
  { from: "orders", to: "shipments", type: "1-1", desc: "مرسوله تحویل فیزیکی" },
  { from: "shipments", to: "shipment_events", type: "1-N", desc: "timeline مرسوله" },
  { from: "orders", to: "payments", type: "1-N", desc: "تلاش‌های پرداخت" },
  { from: "payments", to: "payment_refunds", type: "1-N", desc: "بازپرداخت‌ها" },
  { from: "orders", to: "invoices", type: "1-1", desc: "فاکتور رسمی" },
  { from: "users", to: "notifications", type: "1-N", desc: "اعلان‌ها" },
  { from: "users", to: "tickets", type: "1-N", desc: "تیکت‌های کاربر" },
  { from: "tickets", to: "ticket_messages", type: "1-N", desc: "گفتگو" },
  { from: "users", to: "auto_invest_plans", type: "1-N", desc: "برنامه‌های خرید خودکار" },
  { from: "users", to: "installment_contracts", type: "1-N", desc: "قراردادهای اقساطی" },
  { from: "installment_contracts", to: "installment_payments", type: "1-N", desc: "اقساط" },
  { from: "users", to: "gift_cards", type: "1-N", desc: "هدیه‌های ارسالی" },
  { from: "users", to: "wholesale_orders", type: "1-N", desc: "سفارش عمده نماینده" },
  { from: "users", to: "delivery_requests", type: "1-N", desc: "درخواست تحویل فیزیکی" },
  { from: "users", to: "price_alerts", type: "1-N", desc: "هشدارهای قیمت" },
  { from: "users", to: "buyback_requests", type: "1-N", desc: "بازخریدها" },
];

export const TABLE_GROUPS = ["کاربران", "کاتالوگ", "انبار و خزانه", "قیمت", "کیف پول", "معامله", "فروش", "پشتیبانی", "سیستم"];
